#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v13
# autospec commit: 2659038
#
Name     : R-RcppParallel
Version  : 5.1.8
Release  : 48
URL      : https://cran.r-project.org/src/contrib/RcppParallel_5.1.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/RcppParallel_5.1.8.tar.gz
Summary  : Parallel Programming Tools for 'Rcpp'
Group    : Development/Tools
License  : Apache-2.0 GPL-3.0
Requires: R-RcppParallel-lib = %{version}-%{release}
Requires: R-RcppParallel-license = %{version}-%{release}
Requires: tbb
Requires: tbb-dev
BuildRequires : buildreq-R
BuildRequires : tbb-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
For example, the 'parallelFor()' function can be used to convert the work of
    a standard serial "for" loop into a parallel one and the 'parallelReduce()'
    function can be used for accumulating aggregate or other values.

%package lib
Summary: lib components for the R-RcppParallel package.
Group: Libraries
Requires: R-RcppParallel-license = %{version}-%{release}

%description lib
lib components for the R-RcppParallel package.


%package license
Summary: license components for the R-RcppParallel package.
Group: Default

%description license
license components for the R-RcppParallel package.


%prep
%setup -q -n RcppParallel
pushd ..
cp -a RcppParallel buildavx2
popd
pushd ..
cp -a RcppParallel buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720454334

%install
export SOURCE_DATE_EPOCH=1720454334
rm -rf %{buildroot}
## install_prepend content
export TBB_INC=/usr/include/tbb
export TBB_LIB=/usr/lib64
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/R-RcppParallel
cp %{_builddir}/RcppParallel/src/tbb/COPYING %{buildroot}/usr/share/package-licenses/R-RcppParallel/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/RcppParallel/src/tbb/LICENSE %{buildroot}/usr/share/package-licenses/R-RcppParallel/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/RcppParallel/DESCRIPTION
/usr/lib64/R/library/RcppParallel/INDEX
/usr/lib64/R/library/RcppParallel/Meta/Rd.rds
/usr/lib64/R/library/RcppParallel/Meta/features.rds
/usr/lib64/R/library/RcppParallel/Meta/hsearch.rds
/usr/lib64/R/library/RcppParallel/Meta/links.rds
/usr/lib64/R/library/RcppParallel/Meta/nsInfo.rds
/usr/lib64/R/library/RcppParallel/Meta/package.rds
/usr/lib64/R/library/RcppParallel/NAMESPACE
/usr/lib64/R/library/RcppParallel/NEWS.md
/usr/lib64/R/library/RcppParallel/R/RcppParallel
/usr/lib64/R/library/RcppParallel/R/RcppParallel.rdb
/usr/lib64/R/library/RcppParallel/R/RcppParallel.rdx
/usr/lib64/R/library/RcppParallel/help/AnIndex
/usr/lib64/R/library/RcppParallel/help/RcppParallel.rdb
/usr/lib64/R/library/RcppParallel/help/RcppParallel.rdx
/usr/lib64/R/library/RcppParallel/help/aliases.rds
/usr/lib64/R/library/RcppParallel/help/paths.rds
/usr/lib64/R/library/RcppParallel/html/00Index.html
/usr/lib64/R/library/RcppParallel/html/R.css
/usr/lib64/R/library/RcppParallel/include/RcppParallel.h
/usr/lib64/R/library/RcppParallel/include/RcppParallel/Backend.h
/usr/lib64/R/library/RcppParallel/include/RcppParallel/Common.h
/usr/lib64/R/library/RcppParallel/include/RcppParallel/RMatrix.h
/usr/lib64/R/library/RcppParallel/include/RcppParallel/RVector.h
/usr/lib64/R/library/RcppParallel/include/RcppParallel/TBB.h
/usr/lib64/R/library/RcppParallel/include/RcppParallel/Timer.h
/usr/lib64/R/library/RcppParallel/include/RcppParallel/TinyThread.h
/usr/lib64/R/library/RcppParallel/include/tthread/fast_mutex.h
/usr/lib64/R/library/RcppParallel/include/tthread/tinythread.h
/usr/lib64/R/library/RcppParallel/include/tthread/tinythread.inl
/usr/lib64/R/library/RcppParallel/presentations/header.tex
/usr/lib64/R/library/RcppParallel/presentations/images/big-data-big-machine-tweet.png
/usr/lib64/R/library/RcppParallel/presentations/rcpp_parallel_talk_jan2015.Rmd
/usr/lib64/R/library/RcppParallel/rstudio/templates/project/RcppParallel.package.skeleton.dcf
/usr/lib64/R/library/RcppParallel/skeleton/vector-sum.Rd
/usr/lib64/R/library/RcppParallel/skeleton/vector-sum.cpp
/usr/lib64/R/library/RcppParallel/tests/cpp/distance.cpp
/usr/lib64/R/library/RcppParallel/tests/cpp/innerproduct.cpp
/usr/lib64/R/library/RcppParallel/tests/cpp/sum.cpp
/usr/lib64/R/library/RcppParallel/tests/cpp/transform.cpp
/usr/lib64/R/library/RcppParallel/tests/cpp/truefalse_macros.cpp
/usr/lib64/R/library/RcppParallel/tests/doRUnit.R
/usr/lib64/R/library/RcppParallel/tests/runit.distance.R
/usr/lib64/R/library/RcppParallel/tests/runit.innerproduct.R
/usr/lib64/R/library/RcppParallel/tests/runit.sum.R
/usr/lib64/R/library/RcppParallel/tests/runit.transform.R
/usr/lib64/R/library/RcppParallel/tests/runit.truefalse_macros.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/RcppParallel/libs/RcppParallel.so
/V4/usr/lib64/R/library/RcppParallel/libs/RcppParallel.so
/usr/lib64/R/library/RcppParallel/lib/libtbb.so.12.13
/usr/lib64/R/library/RcppParallel/lib/libtbbbind_2_5.so.3.13
/usr/lib64/R/library/RcppParallel/lib/libtbbmalloc.so.2.13
/usr/lib64/R/library/RcppParallel/lib/libtbbmalloc_proxy.so.2.13
/usr/lib64/R/library/RcppParallel/libs/RcppParallel.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-RcppParallel/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
